import StoreProvider from "@/lib/redux/store/provider";
import WowJsProvider from "@/utils/WowJsProvider";
import "animate.css";
import type { Metadata } from "next";
import { Roboto, Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import Foot from "@/components/ui/Footer";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-Jost",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${jost.variable} antialiased`}>
        <StoreProvider>
          <WowJsProvider>
            <Header/>
            {children}
            <Foot/>
          </WowJsProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
